version: 2

aliases:
  - &ruby
    - image: circleci/ruby:2.6.3

  - &rust
    - image: circleci/rust:latest

  - &restore-cache
    keys:
      - actionmailbox-imap-{{ checksum "Gemfile.lock" }}
      # fallback to using the latest cache if no exact match is found
      - actionmailbox-imap-

  - &save-cache
    paths:
      - ./vendor/bundle
    key: actionmailbox-imap-{{ checksum "Gemfile.lock" }}

defaults: &defaults
  working_directory: ~/actionmailbox-imap

jobs:
  ruby_build:
    <<: *defaults
    docker: &ruby
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-cache

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache: *save-cache

  ruby_test:
    <<: *defaults
    docker: &ruby
    steps:
      - checkout
      - restore_cache: *restore-cache

      # Set bundle path to point to cache
      - run: bundle config --local path vendor/bundle

      # Run the tests
      - run: CI=true ./bin/test

  ruby_lint:
    <<: *defaults
    docker: &ruby
    steps:
      - checkout
      - restore_cache: *restore-cache

      # Set bundle path to point to cache
      - run: bundle config --local path vendor/bundle

      - run: bundle exec standardrb STANDARDOPTS="--format progress"

  rust:
    <<: *defaults
    docker: rust
    steps:
      - checkout
      - restore_cache:
          key: rust-cache
      - run: cargo --check
      - save_cache:
          key: rust-cache
          paths:
            - "~/.cargo"
            - "./target"


workflows:
  version: 2
  build_test_lint:
    jobs:
      - ruby_build
      - ruby_test:
          requires:
            - ruby_build
      - ruby_lint:
          requires:
            - ruby_build
      - rust
