version: 2

aliases:
  - &docker
    - image: circleci/ruby:2.6.3

  - &restore-cache
    keys:
      - actionmailbox-imap-{{ checksum "Gemfile.lock" }}
      # fallback to using the latest cache if no exact match is found
      - actionmailbox-imap-

  - &save-cache
    paths:
      - ./vendor/bundle
    key: actionmailbox-imap-{{ checksum "Gemfile.lock" }}

defaults: &defaults
  working_directory: ~/actionmailbox-imap
  docker: *docker

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-cache

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache: *save-cache

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache

      # Set bundle path to point to cache
      - run: bundle config --local path vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Run the tests
      - run: CI=true ./bin/test

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache

      # Set bundle path to point to cache
      - run: bundle config --local path vendor/bundle

      - run: bundle exec standardrb STANDARDOPTS="--format progress"

workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
