version: 2

aliases:
  - &rubyimg
    - image: circleci/ruby:2.6.3

  - &rustimg
    - image: circleci/rust:latest

  - &restore-ruby-cache
    keys:
      - actionmailbox-imap-ruby-{{ checksum "Gemfile.lock" }}
      # fallback to using the latest cache if no exact match is found
      - actionmailbox-imap-ruby-

  - &save-ruby-cache
    paths:
      - ./vendor/bundle
    key: actionmailbox-imap-ruby-{{ checksum "Gemfile.lock" }}

  - &save-rust-cache
    paths:
      - "~/.cargo"
      - "./target"
    key: actionmailbox-imap-rust-{{ checksum "Cargo.lock" }}

  - &restore-rust-cache
    keys:
      - actionmailbox-imap-rust-{{ checksum "Cargo.lock" }}
      - actionmailbox-imap-rust-

defaults: &defaults
  working_directory: ~/actionmailbox-imap

rust: &rust
  docker: *rustimg

ruby: &ruby
  docker: *rubyimg

jobs:
  ruby_build:
    <<: *defaults
    <<: *ruby
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-ruby-cache

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache: *save-ruby-cache

  ruby_test:
    <<: *defaults
    <<: *ruby
    steps:
      - checkout
      - restore_cache: *restore-ruby-cache

      # Set bundle path to point to cache
      - run: bundle config --local path vendor/bundle

      # Run the tests
      - run: CI=true ./bin/test

  ruby_lint:
    <<: *defaults
    <<: *ruby
    steps:
      - checkout
      - restore_cache: *restore-ruby-cache

      # Set bundle path to point to cache
      - run: bundle config --local path vendor/bundle

      - run: bundle exec standardrb STANDARDOPTS="--format progress"

  rust_build:
    <<: *defaults
    <<: *rust
    steps:
      - checkout
      - save_cache: *save-rust-cache

  rust_test:
    <<: *defaults
    <<: *rust
    steps:
      - checkout
      - restore_cache: *restore-rust-cache
      - run: cargo test

  rust_lint:
    <<: *defaults
    <<: *rust
    steps:
      - checkout
      - restore_cache: *restore-rust-cache
      - run: rustfmt
        - run: cargo fmt --all -- --check

workflows:
  version: 2
  build_test_lint:
    jobs:
      - ruby_build
      - ruby_test:
          requires:
            - ruby_build
      - ruby_lint:
          requires:
            - ruby_build
      - rust_build
      - rust_test:
          requires:
            - rust_build
      - rust_lint:
          requires:
            - rust_build
