server: "***REMOVED***"

# Currently TLS is required
port: 993
tls: true

username: "walter2@kimmel.com"
password: "***REMOVED***"

# The mailbox to select unread messages from
mailbox: "RETRY"

#
# Workers
#
# This is the number of threads used to process
# all unread messages from the IMAP server.
#
# DO NOT use more workers than you have threads available.
workers: 4
