server: "outlook.office365.com"

# Currently TLS is required
port: 993
tls: true

username: "walter2@kimmel.com"
password: "Kimmel trench capon2"

# The mailbox to select unread messages from
mailbox: "RETRY"

#
# Workers
#
# This is the number of threads used to process
# all unread messages from the IMAP server.
#
# DO NOT use more workers than you have threads available.
workers: 4

# Wait (in ms)
#
# Once a server sends the ANY back from waiting
# for activity, you can wait some time before grabbing
# messages. This way the client should grab more than
# just the first message to to trigger activity.
wait: 800

url: 
ingress_password:
